services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: palindrome_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///palindrome.db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]